### PR TITLE
Fixes issue #15 in 2_svs_to_jpg_tiles.py

### PR DESCRIPTION
**Pull request by mbluestone**
Patch creation increment along x and y now accounts for cases where the image size is divisible by the window size.

### CODE REVIEW

**Comment by ntomita** [comment]
@mbluestone Maybe better use `int(math.ceil(height/window_size))`. What do you think?

**Comment by mbluestone** [comment]
Yeah sounds good! I just made the change.

**Comment by ntomita** [comment]
@mbluestone thanks for the update. I think you can even remove the if-else statement because when `height % window_size == 0` , `height / window_size` must be an integer and `ceil()` does nothing and returns the original integer value. Try it out and let me know if that works.

**Comment by mbluestone** [comment]
Ah yeah definitely - that works

**Pull request merged**
